CREATE TABLE IF NOT EXISTS messages (
	id SERIAL PRIMARY KEY,
  sent_date TIMESTAMPTZ NOT NULL,
	contents TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS rooms (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT NOT NULL
);
